### PR TITLE
make room in websocket namespace for end user proxies

### PR DESCRIPTION
**Pull request by TomzBench**
## What I did

1. Move websocket from `/` to `wds`

### CODE REVIEW

**Comment by stephenwade** [comment]
Thanks @TomzBench! Please rebase this on master and [add a changeset](https://github.com/modernweb-dev/web/blob/master/CONTRIBUTING.md#create-a-changeset).

**Comment by TomzBench** [comment]
@stephenwade I rebased and hope I added change set correctly.

Thanks,

**Comment by stephenwade** [comment]
Thanks! Can you fix the tests?

**Comment by TomzBench** [comment]
@stephenwade I think I fixed the tests. I'm not sure how to run tests locally (I get some errors when running npm test commands). I only changed the tests that I thought would be affected but i'm not familiar at all with the code base. so it won't be clear to me if other tests are affected by this websocket api change.

**Comment by LarsDenBakker** [comment]
We use yarn workspaces, so you need to use `yarn test` for running the tests. I retried the CI though, it looks like a CI error.

**Comment by LarsDenBakker** [comment]
All green now, except we now have a merge conflict :(

**Comment by stephenwade** [comment]
@LarsDenBakker I don't see a merge conflict?

GitHub merge UI with the message 'This branch has no conflicts with the base branch'

**Comment by LarsDenBakker** [comment]
Ah, it did complain about it when rebasing but we want to do a squash here anyway.

**Pull request merged**
