### PR TITLE
fix(rollup-plugin-import-meta-assets): add ESM entrypoint with .mjs file

### PR DESCRIPTION
**Pull request by hsablonniere**
I was having this error:

```
[!] Error: Cannot find module '/home/hsablonniere/dev/clever-components/node_modules/@web/rollup-plugin-import-meta-assets/dist/index.js'. Please verify that the package.json has a valid "main" entry
```

### CODE REVIEW

**Comment by daKmoR** [comment]
what node version are you using? the existing "exports" field in package.json should be picked up by node 12 and 14 🤔

**Comment by LarsDenBakker** [comment]
Indeed, the module field is for bundlers

**Comment by hsablonniere** [comment]
* Node.js 14.6.0
* npm 6.14.6

**Comment by daKmoR** [comment]
> Indeed, the module field is for bundlers

yeah I keep forgetting that rollup still does not support the exports field 🙈

**Comment by hsablonniere** [comment]
The project in which I'm using the module has `"type": "module"`.

**Comment by hsablonniere** [comment]
OK, my bad, the bug is fixed with this: https://github.com/modernweb-dev/web/commit/68e24b6900cea9a3eb1d2f6767b2a278ce13d451

It's just that the fix is not released yet.

**Comment by LarsDenBakker** [comment]
My bad, I submitted the fix but didn't merge the version change PR from changesets. It's running now!

**Pull request closed without merging**
