### PR TITLE
feat/various fixes

### PR DESCRIPTION
**Pull request by thepassle**
## What I did

1. Update puppeteer to 20.0.0, fixes https://github.com/modernweb-dev/web/issues/2282
2. Use puppeteer's new `page.mouse.reset()` in `sendMousePlugin`, fixes https://github.com/modernweb-dev/web/issues/2262
3. Use `development` export condition by default

### CODE REVIEW

**Comment by thepassle** [comment]
@tmsns FYI the focus tests are still failing, I'm skipping them for now

image

**Comment by daKmoR** [comment]
needs a rebase for the conflict... but rest LGTM 👍

**Comment by koddsson** [comment]
Does this also need a changeset, so it's released?

**Comment by thepassle** [comment]
Huh, weird, pretty sure I added a changeset. Maybe I fudged something. I'll re-add the changeset.

**Comment by bearfriend** [comment]
The switch to `development` exports caused some minor issues for us. Easy enough to work around but I was just curious what the reasoning was for this switch. It doesn't seem like it's linked to any issues like the other fixes.

**Comment by bearfriend** [comment]
Sure. We have some `lit` components that have their own `_initialize` methods. Those of course extend `LitElement` (which itself extend `ReactiveElement`), and eventually tries to initialize itself with `this._initialize()`. With `development` exports, though, this doesn't get renamed, so they collide and `ReactiveElement` ends up calling _my_ `_initialize` method instead.

Using `development` exports by default seems like there is no limit to the things that could collide if they're being extended, and the devs of those packages would/should fully expect that not to be an issue, so that could start happening even with minor or patch releases.

**Comment by thepassle** [comment]
Cc @justinfagnani this feedback may be of interest to you

**Comment by justinfagnani** [comment]
Sounds like this highlighted some real problems in user code!

fwiw, I tried to change `_initialize` to avoid collisions: https://github.com/lit/lit/pull/3895 but we had to revert that specific PR. I can take another shot with a different approach, which will alleviate this issue.

**Comment by bearfriend** [comment]
I suppose I'm still a bit confused as to why we want to default to `development`. With no other setup, nothing else would resolve to `development` exports. The `default` export should always be the ~transpiled version (and in lit it is), no? To default the conditions to anything that isn't `default` seems odd.

Perhaps I'm misunderstanding something, though.

**Comment by bearfriend** [comment]
Also, I'm not sure why this would be considered a problem with user code, since `_initialize` is not a documented public method of the class.

**Comment by augustjk** [comment]
> I suppose I'm still a bit confused as to why we want to default to `development`.

I'm for development condition being default as this is web *dev* server, after all. Some libraries like Lit have extra checks and warnings that only show in dev mode, it's nice to be able to see those while developing. I feel like it probably should default to the production build for testing though.

**Comment by bearfriend** [comment]
> as this is web dev server, after all. ...  I feel like it probably should default to the production build for testing though.

Thanks for pointing this out. I _was_ thinking about this just from the testing side. I agree with all of that.

**Pull request merged**
