### PR TITLE
fix(browser-logs): fix print promises issue

### PR DESCRIPTION
**Pull request by ashikvarma11**
### Added
1. Displaying `Promise { }` while logging a Promise after deserialization.
2. Changes in `serialize.ts` and `deserialize.ts` files.
3. Test cases in `browser-logs.test.ts`

### CODE REVIEW

**Comment by LarsDenBakker** [comment]
Looks good to me! We have some linting errors though.

**Comment by ashikvarma11** [comment]
> Looks good to me! We have some linting errors though.

@LarsDenBakker  Verification for BrowserStack and SauceLabes is failing. Both showing the same error in console. I'm not able to figure out the issue. Could you guide me through this?
```

D:\Projects\web\packages\test-runner-browserstack\test-remote\browserstackLauncher.test.js:14
  build: `modern-web ${process.env.GITHUB_REF ?? 'local'} build ${
                                               ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.exports.requireOrImport (D:\Projects\web\node_modules\mocha\lib\esm-utils.js:20:12)
    at Object.exports.loadFilesAsync (D:\Projects\web\node_modules\mocha\lib\esm-utils.js:33:34)
    at Mocha.loadFilesAsync (D:\Projects\web\node_modules\mocha\lib\mocha.js:427:19)
    at singleRun (D:\Projects\web\node_modules\mocha\lib\cli\run-helpers.js:156:15)
    at exports.runMocha (D:\Projects\web\node_modules\mocha\lib\cli\run-helpers.js:225:10)
    at Object.exports.handler (D:\Projects\web\node_modules\mocha\lib\cli\run.js:366:11)
    at D:\Projects\web\node_modules\mocha\node_modules\yargs\lib\command.js:241:49
error Command failed with exit code 1.
```

**Comment by ashikvarma11** [comment]
> > Looks good to me! We have some linting errors though.
> 
> @LarsDenBakker Verification for BrowserStack and SauceLabes is failing. Both showing the same error in console. I'm not able to figure out the issue. Could you guide me through this? Should I add anything to environment variables?
> 
> ```
> 
> D:\Projects\web\packages\test-runner-browserstack\test-remote\browserstackLauncher.test.js:14
>   build: `modern-web ${process.env.GITHUB_REF ?? 'local'} build ${
>                                                ^
> 
> SyntaxError: Unexpected token '?'
>     at wrapSafe (internal/modules/cjs/loader.js:1054:16)
>     at Module._compile (internal/modules/cjs/loader.js:1102:27)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
>     at Module.load (internal/modules/cjs/loader.js:986:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
>     at Module.require (internal/modules/cjs/loader.js:1026:19)
>     at require (internal/modules/cjs/helpers.js:72:18)
>     at Object.exports.requireOrImport (D:\Projects\web\node_modules\mocha\lib\esm-utils.js:20:12)
>     at Object.exports.loadFilesAsync (D:\Projects\web\node_modules\mocha\lib\esm-utils.js:33:34)
>     at Mocha.loadFilesAsync (D:\Projects\web\node_modules\mocha\lib\mocha.js:427:19)
>     at singleRun (D:\Projects\web\node_modules\mocha\lib\cli\run-helpers.js:156:15)
>     at exports.runMocha (D:\Projects\web\node_modules\mocha\lib\cli\run-helpers.js:225:10)
>     at Object.exports.handler (D:\Projects\web\node_modules\mocha\lib\cli\run.js:366:11)
>     at D:\Projects\web\node_modules\mocha\node_modules\yargs\lib\command.js:241:49
> error Command failed with exit code 1.
> ```

**Comment by LarsDenBakker** [comment]
Those are expected, it's because you're missing the credentials on your fork.

**Comment by LarsDenBakker** [comment]
Can you run `yarn changeset` and create a patch for the browser logs package?

**Comment by LarsDenBakker** [comment]
The changelog is auto generated, no need to add it. Other than that we're good to go!

**Comment by ashikvarma11** [comment]
> The changelog is auto generated, no need to add it. Other than that we're good to go!

Yes.  I did `yarn changeset` and added the description and committed it. Also added description in browser-logs/CHANGELOG.md. This was in the second-last commit.

**Comment by LarsDenBakker** [comment]
Sorry for the confusion, but we don't need to add things manually to changelog. This is done when the version is bumped by changeset. Could you remove the change? 🙏

**Comment by LarsDenBakker** [comment]
Thanks!

**Pull request merged**
