### PR TITLE
 fix(rollup-plugin-import-meta-assets): fix warn() code when error was caught

### PR DESCRIPTION
**Pull request by hsablonniere**

### CODE REVIEW

**Comment by LarsDenBakker** [comment]
Looks good. We need to add a changeset (`yarn changeset`) to create a release, and there is a formatting linting error in the CI.

**Comment by hsablonniere** [comment]
My first time submitting a changeset :thinking: ...

**Comment by hsablonniere** [comment]
@LarsDenBakker I split the changes in two, test and fix, I'm not sure about that, let me know.

**Comment by hsablonniere** [comment]
@LarsDenBakker 🎉

**Pull request merged**
