### PR TITLE
set node version to 18

### PR DESCRIPTION
**Pull request by koddsson**
## What I did

1. I set `engines.node` version to at least 18.

I figured since we aren't even testing on node16 that we don't actually support it.

### CODE REVIEW

**Comment by koddsson** [comment]
Would this be all breaking changes? 🤔

**Comment by bashmish** [comment]
> Would this be all breaking changes? 🤔

Theoretically. But for pragmatic reasons I'd keep it a patch

**Review by bashmish — APPROVED** [review]
Makes sense to me indeed!

**Comment by koddsson** [comment]
> Makes sense to me indeed!

Nice! I'll update the versions to be a minor bump and if no one else chimes in soon I'll release this 👍🏻

**Pull request merged**
