### PR TITLE
Promote Canary releases to master

### PR DESCRIPTION
**Pull request by Westbrook**
## What we did

1. Rollup@v3
2. Updated rollup plugin versions
3. Updated LRU Cache
4. Use LRU Cache to the code coverage workflow
5. Removes testing for Node@14 (ends maintenance period next month) This is technically a break, did we catch all the version changes in the changeset @43081j?
6. Adds testing for Node@19
7. Mocha@v10

### CODE REVIEW

**Comment by 43081j** [comment]
I think we only have a changeset for the individual lru pr. We need to add one (or many) for the node support change. 

I'm away on vacation at the min though so won't be able to add those until next week at least. If you know what to do, feel free

**Comment by Westbrook** [comment]
@43081j enjoy your holiday! When you're back, I wonder if you've seen this: https://github.com/modernweb-dev/web/issues/2132 in your testing. We're starting to see some good perf updates with these changes, but whatever underlying situation exists there might require us to continue to force prevent caching. 😢

**Comment by Westbrook** [comment]
This is starting to feel ready to go! Testing in OpenWC is here: https://github.com/open-wc/open-wc/pull/2649

@koddsson are you seeing the Mocha changes as breaking, still? I think that would be the last thing to wait for on this branch, assuming it's working for everyone as expected in their local test.

SWC is seeing great things with this update: https://app.circleci.com/pipelines/github/adobe/spectrum-web-components/15272/workflows/3acdf8ac-1afd-4d81-b9d2-8f8a8c26c57d We're seeing real benefits from the various performance improvements included herein!

**Comment by koddsson** [comment]
> @koddsson are you seeing the Mocha changes as breaking, still?

Yeah, the branch `update-mocha` doesn't update all the dependencies to version 10. I run into issues when updating the last one.

```
 ~/src/koddsson/web/ [update-mocha] npm ls mocha
@web/root@ /Users/cr91ew/src/koddsson/web
├─┬ @web/test-runner-commands@0.6.5 -> ./packages/test-runner-commands
│ └── mocha@10.2.0
├─┬ @web/test-runner-mocha@0.7.5 -> ./packages/test-runner-mocha
│ └── mocha@10.2.0
├─┬ @web/test-runner-visual-regression@0.7.0 -> ./packages/test-runner-visual-regression
│ └── mocha@10.2.0
└── mocha@8.4.0
```

I haven't figured it out and haven't found the time to really dive into it yet. It might be best to continue without the mocha updates and come back to them later.

**Comment by koddsson** [comment]
Are we ready to land this? I would have liked to get the mocha stuff in but I can't seem to figure it out.

**Comment by 43081j** [comment]
what problem are you having exactly? with mocha

happy to take a look if you can point me the right direction to a failed build somewhere

**Comment by Westbrook** [comment]
I was hoping we could sneak in the Mocha update, but am pretty OK with moving forward. Maybe let @43081j have a run at it and were that not immediately productive we do the thing?

**Comment by koddsson** [comment]
> what problem are you having exactly? with mocha
> 
> happy to take a look if you can point me the right direction to a failed build somewhere

Sure! Here's the PR: https://github.com/modernweb-dev/web/pull/2177

**Comment by koddsson** [comment]
A photo of a hand-mounted toy shark in a kitchen. The shark has a chefs hat and below the image it's written: "It's ready!"

**Comment by koddsson** [comment]
```
🦋  @web/browser-logs@0.0.0-canary-20230416222938
🦋  @web/config-loader@0.0.0-canary-20230416222938
🦋  @web/dev-server@0.0.0-canary-20230416222938
🦋  @web/dev-server-core@0.0.0-canary-20230416222938
🦋  @web/dev-server-esbuild@0.0.0-canary-20230416222938
🦋  @web/dev-server-hmr@0.0.0-canary-20230416222938
🦋  @web/dev-server-import-maps@0.0.0-canary-20230416222938
🦋  @web/dev-server-legacy@0.0.0-canary-20230416222938
🦋  @web/dev-server-rollup@0.0.0-canary-20230416222938
🦋  @web/dev-server-storybook@0.0.0-canary-20230416222938
🦋  @web/parse5-utils@0.0.0-canary-20230416222938
🦋  @web/polyfills-loader@0.0.0-canary-20230416222938
🦋  @web/rollup-plugin-copy@0.0.0-canary-20230416222938
🦋  @web/rollup-plugin-html@0.0.0-canary-20230416222938
🦋  @web/rollup-plugin-import-meta-assets@0.0.0-canary-20230416222938
🦋  @web/rollup-plugin-polyfills-loader@0.0.0-canary-20230416222938
🦋  rollup-plugin-workbox@0.0.0-canary-20230416222938
🦋  @web/test-runner@0.0.0-canary-20230416222938
🦋  @web/test-runner-browserstack@0.0.0-canary-20230416222938
🦋  @web/test-runner-chrome@0.0.0-canary-20230416222938
🦋  @web/test-runner-cli@0.0.0-canary-20230416222938
🦋  @web/test-runner-commands@0.0.0-canary-20230416222938
🦋  @web/test-runner-core@0.0.0-canary-20230416222938
🦋  @web/test-runner-coverage-v8@0.0.0-canary-20230416222938
🦋  @web/test-runner-junit-reporter@0.0.0-canary-20230416222938
🦋  @web/test-runner-mocha@0.0.0-canary-20230416222938
🦋  @web/test-runner-playwright@0.0.0-canary-20230416222938
🦋  @web/test-runner-puppeteer@0.0.0-canary-20230416222938
🦋  @web/test-runner-saucelabs@0.0.0-canary-20230416222938
🦋  @web/test-runner-selenium@0.0.0-canary-20230416222938
🦋  @web/test-runner-visual-regression@0.0.0-canary-20230416222938
🦋  @web/test-runner-webdriver@0.0.0-canary-20230416222938
```

**Comment by koddsson** [comment]
I've tested these locally and it looks great to me.

**Comment by Westbrook** [comment]
@43081j give a holler if this is looking good for you as well.

**Comment by 43081j** [comment]
looks good to me, have also tried it again on our larger codebase and all seems fine

**Comment by koddsson** [comment]
Do we merge this now? That won't create a release, right? We then need to merge the `changeset` PR that gets created.

**Pull request merged**
